### ISSUE TITLE
Wrong video

### ISSUE THREAD

**Issue by dpriskorn** [nayyhah/Decipher#1]
I send it a link to a <1min YT video: https://www.youtube.com/watch?v=iS6aFzceFzs and another video appeared after a few minutes. The language spoken was not the one choosen either (I choose Danish)

**Comment by nayyhah** [comment]
The issues are due to some errors in the hosting of the website. The project runs fine in the local set up so you can check it by cloning the repo instead. 

Hope that helps. Thank you.
